spring.application.name=portal

# Server Port (Render automatically sets the PORT variable)
server.port=${PORT:8080}

# MySQL Connection Settings (Fetches values from Render Environment Variables with local fallbacks)
# Database Connection Settings
spring.datasource.url=${DB_URL:jdbc:h2:mem:placement_portal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2408c692257d00f68d60d3d3a0c5c3c0a
jwt.expiration=36000000